name: cron job
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  
jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: py script secrets check
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SUPABASE_URI: ${{ secrets.SUPABASE_URI }}
        run: |
          python strava-keys.py

